### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by bknutson123** [byu-oit/terraform-aws-standard-fargate#5]

**Comment by bknutson123** [comment]
container_image_url also doesnt exist in the readme and that one is required so we should probably put it in the example as well

**Comment by bknutson123** [comment]
also dockerfile_dir should be removed

**Comment by bknutson123** [comment]
health_check_grace_period does not exist in readme as input variable

**Comment by jvisker** [comment]
@yoshutch fixed these.
